server:
  port: 8020
eureka:
  client:
    service-url:
     defaultZone: http://localhost:9090/eureka,http://localhost:9091/eureka,http://localhost:9092/eureka
spring:
  application:
    name: consumer